plugins {
    id 'java-test-fixtures'
    id 'jvm-test-suite'
    id 'groovy'
}

testing {
    suites {
        configureEach { suite ->
            if (suite.name.endsWith("Test") || suite.name.equals('test')) {
                useJUnitJupiter(libs.versions.junit.get())
                useSpock(libs.versions.spock.get())
                dependencies {
                    implementation(platform(libs.groovy.bom))
                    implementation(platform(libs.junit.bom))
                    implementation(platform(libs.spock.bom))
                    runtimeOnly(libs.objenesis)
                    implementation(libs.groovy)

                    // generally avoid implementing tests based in JUnit, use Spock
                    implementation(libs.junit.jupiter.api)
                    implementation(libs.junit.jupiter)
                    runtimeOnly(libs.junit.platform.launcher)

                }
            }
            if (suite.name.endsWith('Test')) {
                targets {
                    all {
                        testTask.configure {
                            shouldRunAfter(test)
                        }
                    }
                }
            }
        }
        if (file('src/integrationTest').exists()) {
            integrationTest(JvmTestSuite) {
                configurations {
                    named(sources.implementationConfigurationName) {
                        extendsFrom(getByName(JavaPlugin.IMPLEMENTATION_CONFIGURATION_NAME))
                    }
                }
                dependencies {
                    implementation (platform(libs.spring.boot.dependencies))
                    implementation (libs.spring.boot.starter.actuator.test)
                    implementation (libs.spring.boot.starter.data.jpa.test)
                    implementation (libs.spring.boot.starter.flyway.test)
                    implementation (libs.spring.boot.starter.opentelemetry.test)
                    implementation (libs.spring.boot.starter.webmvc.test)
                    implementation (libs.spring.boot.testcontainers)
                    implementation (platform(libs.spring.modulith.bom))
                    implementation (libs.spring.modulith.starter.test)
                    implementation (libs.testcontainers.grafana)
                    implementation (libs.testcontainers.junit.jupiter)
                    implementation (libs.testcontainers.postgresql)
                    implementation (project())
                    implementation (testFixtures(project(':')))
                }
            }
        }
    }
}

tasks.named('check') {
    dependsOn(testing.suites.integrationTest)
}

dependencies {
    testFixturesImplementation(platform(libs.groovy.bom))
    testFixturesImplementation(libs.groovy)
}