application:
  name: bootolithic
  title: bootolithic

cors:
  allowed-origins: "http://localhost:8080"

server:
  servlet:
    context-path: /api

spring:
  sql:
    init:
      mode: always
  flyway:
    # Make sure that setting never makes into a production environment!
    clean-disabled: false
  modulith:
    runtime:
      flyway-enabled: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.SQL: DEBUG


debug: true