#
# Keep all elements in alphabetical order!
#

[versions]
benmanes-versions = "0.53.0"
build-health = "3.5.1"
byte-buddy = "1.18.4"

cyclonedx-bom = "3.1.0"

gradle-git-properties = "2.5.4"

groovy = "5.0.4"

hypersistence-utils-hibernate = "3.14.1"
hypersistence-tsid = "2.1.4"

java = "25"
jilt = "1.9.1"
jmolecules = "2025.0.2"
junit = "6.0.2"

lombok = "1.18.36"

mapstruct = "1.6.3"
moneta = "1.4.5"
money-api = "1.1"

spock = "2.4-groovy-5.0"

spring-boot = "4.0.1"

spring-hateoas-jsonapi = "3.1.0"

spring-modulith-bom = "2.0.1"

testcontainer-keycloak = "3.4.0"

[libraries]

commons-lang3 = { module = "org.apache.commons:commons-lang3" }

flyway-database-postgresql = { module = "org.flywaydb:flyway-database-postgresql" }

groovy-bom = { module = "org.apache.groovy:groovy-bom", version.ref = "groovy" }
groovy = { module = "org.apache.groovy:groovy" }

hibernate-core = { module = "org.hibernate.orm:hibernate-core" }
hypersistence-utils-hibernate = { module = "io.hypersistence:hypersistence-utils-hibernate-71", version.ref = "hypersistence-utils-hibernate" }
hypersistence-tsid = { module = "io.hypersistence:hypersistence-tsid", version.ref = "hypersistence-tsid" }

jackson-datatype-moneta = { module = "tools.jackson.datatype:jackson-datatype-moneta" }
jackson-datatype-javax-money = { module = "tools.jackson.datatype:jackson-datatype-javax-money" }

jakarta-persistence-api = { module = "jakarta.persistence:jakarta.persistence-api" }

jilt = { module = "cc.jilt:jilt", version.ref = "jilt" }

jmolecules-bom = { module = "org.jmolecules:jmolecules-bom", version.ref = "jmolecules" }
jmolecules-jackson3 = { module = "org.jmolecules.integrations:jmolecules-jackson3" }
jmolecules-jpa = { module = "org.jmolecules.integrations:jmolecules-jpa" }
jmolecules-spring = { module = "org.jmolecules.integrations:jmolecules-spring" }
jmolecules-starter-ddd = { module = "org.jmolecules.integrations:jmolecules-starter-ddd" }
jmolecules-ddd = { module = "org.jmolecules:jmolecules-ddd" }
jmolecules-ddd-integration = { module = "org.jmolecules.integrations:jmolecules-ddd-integration" }
jmolecules-bytebuddy-nodep = { module = "org.jmolecules.integrations:jmolecules-bytebuddy-nodep" }

jspecify = { module = "org.jspecify:jspecify" }

junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
lombok-mapstruct-binding = { module = "org.projectlombok:lombok-mapstruct-binding", version = "0.2.0" }

mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstruct" }

moneta = { module = "org.javamoney:moneta", version.ref = "moneta" }
money-api = { module = "javax.money:money-api", version.ref = "money-api" }

objenesis = { module = "org.objenesis:objenesis", version = "3.4" }

postgresql = { module = "org.postgresql:postgresql" }

spock-bom = { module = "org.spockframework:spock-bom", version.ref = "spock" }
spock-spring = { module = "org.spockframework:spock-spring" }

spring-beans = { module = "org.springframework:spring-beans" }
spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor" }
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-actuator-test = { module = "org.springframework.boot:spring-boot-starter-actuator-test" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-data-jpa-test = { module = "org.springframework.boot:spring-boot-starter-data-jpa-test" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-boot-starter-security-oauth2-client = { module = "org.springframework.boot:spring-boot-starter-security-oauth2-client" }
spring-boot-starter-security-oauth2-client-test = { module = "org.springframework.boot:spring-boot-starter-security-oauth2-client-test" }
spring-boot-starter-security-oauth2-resource-server = { module = "org.springframework.boot:spring-boot-starter-security-oauth2-resource-server" }
spring-boot-starter-security-oauth2-resource-server-test = { module = "org.springframework.boot:spring-boot-starter-security-oauth2-resource-server-test" }
spring-boot-starter-security-test = { module = "org.springframework.boot:spring-boot-starter-security-test" }
spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }
spring-boot-starter-webflux-test = { module = "org.springframework.boot:spring-boot-starter-webflux-test" }
spring-boot-devtools = { module = "org.springframework.boot:spring-boot-devtools" }
spring-boot-hibernate = { module = "org.springframework.boot:spring-boot-hibernate" }
spring-boot-jdbc-test = { module = "org.springframework.boot:spring-boot-jdbc-test" }
spring-boot-docker-compose = { module = "org.springframework.boot:spring-boot-docker-compose" }
spring-boot-starter-flyway = { module = "org.springframework.boot:spring-boot-starter-flyway" }
spring-boot-starter-flyway-test = { module = "org.springframework.boot:spring-boot-starter-flyway-test" }
spring-boot-starter-json = { module = "org.springframework.boot:spring-boot-starter-json" }
spring-boot-starter-logging = { module = "org.springframework.boot:spring-boot-starter-logging" }
spring-boot-starter-opentelemetry = { module = "org.springframework.boot:spring-boot-starter-opentelemetry" }
spring-boot-starter-opentelemetry-test = { module = "org.springframework.boot:spring-boot-starter-opentelemetry-test" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-webmvc = { module = "org.springframework.boot:spring-boot-starter-webmvc" }
spring-boot-starter-webmvc-test = { module = "org.springframework.boot:spring-boot-starter-webmvc-test" }
spring-boot-testcontainers = { module = "org.springframework.boot:spring-boot-testcontainers" }
spring-context = { module = "org.springframework:spring-context" }
spring-data-commons = { module = "org.springframework.data:spring-data-commons" }

spring-hateoas-jsonapi = { module = "com.toedter:spring-hateoas-jsonapi", version.ref = "spring-hateoas-jsonapi" }
spring-hateoas = { module = "org.springframework.hateoas:spring-hateoas" }

spring-modulith-bom = { module = "org.springframework.modulith:spring-modulith-bom", version.ref = "spring-modulith-bom" }
spring-modulith-actuator = { module = "org.springframework.modulith:spring-modulith-actuator" }
spring-modulith-api = { module = "org.springframework.modulith:spring-modulith-api" }
spring-modulith-core = { module = "org.springframework.modulith:spring-modulith-core" }
spring-modulith-docs = { module = "org.springframework.modulith:spring-modulith-docs" }
spring-modulith-observability = { module = "org.springframework.modulith:spring-modulith-observability" }
spring-modulith-runtime = { module = "org.springframework.modulith:spring-modulith-runtime" }
spring-modulith-starter-core = { module = "org.springframework.modulith:spring-modulith-starter-core" }
spring-modulith-starter-jpa = { module = "org.springframework.modulith:spring-modulith-starter-jpa" }
spring-modulith-starter-test = { module = "org.springframework.modulith:spring-modulith-starter-test" }
spring-test = { module = "org.springframework:spring-test" }

testcontainers-grafana = { module = "org.testcontainers:testcontainers-grafana" }
testcontainers-junit-jupiter = { module = "org.testcontainers:testcontainers-junit-jupiter" }
testcontainers-keycloak = { module = "com.github.dasniko:testcontainers-keycloak", version.ref = "testcontainer-keycloak" }
testcontainers-postgresql = { module = "org.testcontainers:testcontainers-postgresql" }

[plugins]
benmanes-versions = { id = "com.github.ben-manes.versions", version.ref = "benmanes-versions" }
build-health = { id = "com.autonomousapps.build-health", version.ref = "build-health" }
byte-buddy = { id = "net.bytebuddy.byte-buddy-gradle-plugin", version.ref = "byte-buddy" }
cyclonedx-bom = { id = "org.cyclonedx.bom", version.ref = "cyclonedx-bom" }
gradle-git-properties = { id = "com.gorylenko.gradle-git-properties", version.ref = "gradle-git-properties" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
